<?php

declare(strict_types=1);

use Phinx\Seed\AbstractSeed;

class InstitutionsSeeder extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     */
    public function run(): void
    {
        $data = [
            ['name' => 'RA NURUL YAQIN', 'level' => 'tk'],
            ['name' => 'RA AL-ISLAM', 'level' => 'tk'],
            ['name' => 'RA AL MUSYAHADAH SUMURWATU', 'level' => 'tk'],
            ['name' => 'RA DARUL ARQOM', 'level' => 'tk'],
            ['name' => 'RA NURUL IHSAN', 'level' => 'tk'],
            ['name' => 'RA ASY-SYIFA', 'level' => 'tk'],
            ['name' => 'RA BANI WITRI AL-MAKSUM', 'level' => 'tk'],
            ['name' => 'RA AL-ABROOR', 'level' => 'tk'],
            ['name' => 'RA SEKOLAH ALAM INDRAMAYU', 'level' => 'tk'],
            ['name' => 'RA AR-RISALAH', 'level' => 'tk'],
            ['name' => 'RA AL FAJAR', 'level' => 'tk'],
            ['name' => 'RA RAUDLATUL HUDA', 'level' => 'tk'],
            ['name' => 'RA SEKAR FAJAR', 'level' => 'tk'],
            ['name' => 'RA NURUL HIKMAH HAURGEULIS', 'level' => 'tk'],
            ['name' => 'RA NURUL HUDA SIDADADI', 'level' => 'tk'],
            ['name' => 'RA NURUL YAQIN', 'level' => 'tk'],
            ['name' => 'RA SALSABILA CIPAAT', 'level' => 'tk'],
            ['name' => 'RA DARURROHMAH', 'level' => 'tk'],
            ['name' => 'RA AL MUSYAFFALLAH', 'level' => 'tk'],
            ['name' => 'RA MADINATUL HUDA', 'level' => 'tk'],
            ['name' => 'RA ANWARUSSUNNAH', 'level' => 'tk'],
            ['name' => 'RA MUTA`ALIMIN II', 'level' => 'tk'],
            ['name' => 'RA HUSNUL KHOTIMAH', 'level' => 'tk'],
            ['name' => 'RA AL FALAHIYAH BUGEL', 'level' => 'tk'],
            ['name' => 'RA ISLAMIYAH KEDOKAN GABUS', 'level' => 'tk'],
            ['name' => 'RA BI`TSATUL ISLAMIYAH', 'level' => 'tk'],
            ['name' => 'RA AL HIDAYAH', 'level' => 'tk'],
            ['name' => 'RA ALL-ITTIHAD', 'level' => 'tk'],
            ['name' => 'RA AL HUDA', 'level' => 'tk'],
            ['name' => 'RA HIDAYATUSSHIBYAN', 'level' => 'tk'],
            ['name' => 'RA RAUDLOTUN NASYIIN', 'level' => 'tk'],
            ['name' => 'RA NURUL HUDA', 'level' => 'tk'],
            ['name' => 'RA ANNIDLOMIYYAH', 'level' => 'tk'],
            ['name' => 'RA AL ADIIB', 'level' => 'tk'],
            ['name' => 'RA AS SYIFA', 'level' => 'tk'],
            ['name' => 'RA NU', 'level' => 'tk'],
            ['name' => 'RA AL HIDAYAH', 'level' => 'tk'],
            ['name' => 'RA ANDALAN', 'level' => 'tk'],
            ['name' => 'RA TAZKIAH', 'level' => 'tk'],
            ['name' => 'RA AL AMANAH', 'level' => 'tk'],
            ['name' => 'RA HIDAYATUL MUHSININ', 'level' => 'tk'],
            ['name' => 'RA/BA/TA-ALFATAH', 'level' => 'tk'],
            ['name' => 'RA NURUL ANSHOR', 'level' => 'tk'],
            ['name' => 'RA AL-FALAH', 'level' => 'tk'],
            ['name' => 'RA BANI YASIN', 'level' => 'tk'],
            ['name' => 'RA AL-MAKMUR', 'level' => 'tk'],
            ['name' => 'RA NU CANTIGI', 'level' => 'tk'],
            ['name' => 'RA YA ABIDI', 'level' => 'tk'],
            ['name' => 'RA NURUZZAMAN', 'level' => 'tk'],
            ['name' => 'RA AL FUTUHIYAH', 'level' => 'tk'],
            ['name' => 'RA AL-WARDAH', 'level' => 'tk'],
            ['name' => 'RA SITI AMINAH', 'level' => 'tk'],
            ['name' => 'RA DARUNNAJAH', 'level' => 'tk'],
            ['name' => 'RA AL-BARKAH', 'level' => 'tk'],
            ['name' => 'RA AL MANAR BUSTANUL ATHFAL', 'level' => 'tk'],
            ['name' => 'RA AL-WASHLIYAH', 'level' => 'tk'],
            ['name' => 'RA AL-MUTA`ALLIMIN', 'level' => 'tk'],
            ['name' => 'RA RABITHATUL ULUM', 'level' => 'tk'],
            ['name' => 'RA DARUSSHIBYAN', 'level' => 'tk'],
            ['name' => 'RA ASY-SYAFI`IYYAH', 'level' => 'tk'],
            ['name' => 'RA BITSATUL ISLAMIYAH', 'level' => 'tk'],
            ['name' => 'RA AL-FALAH', 'level' => 'tk'],
            ['name' => 'RA AL ISLAHIYAH', 'level' => 'tk'],
            ['name' => 'RA DARUL FALAH', 'level' => 'tk'],
            ['name' => 'RA AL-AMIN', 'level' => 'tk'],
            ['name' => 'RA TARBIYATUL ISLAMIYAH', 'level' => 'tk'],
            ['name' => 'RA FATHUL ULUM', 'level' => 'tk'],
            ['name' => 'RA HIKMATULLAH', 'level' => 'tk'],
            ['name' => 'RA MAS UDIYAH', 'level' => 'tk'],
            ['name' => 'RA NURUL HIDAYAH', 'level' => 'tk'],
            ['name' => 'RA TANWIRUL ATHFAL', 'level' => 'tk'],
            ['name' => 'RA MIFTAHUL MUBTADIIN', 'level' => 'tk'],
            ['name' => 'RA AL ISTIQOMAH', 'level' => 'tk'],
            ['name' => 'RA MIFTAHUL HUDA', 'level' => 'tk'],
            ['name' => 'RA AL AMIN', 'level' => 'tk'],
            ['name' => 'RA AL HIDAYAH', 'level' => 'tk'],
            ['name' => 'RA MIFTAHUL HUDA', 'level' => 'tk'],
            ['name' => 'RA RAUD MUBTADI IN', 'level' => 'tk'],
            ['name' => 'RA SUBULUS SALAM', 'level' => 'tk'],
            ['name' => 'RA NURHIDAYAH', 'level' => 'tk'],
            ['name' => 'RA NURUSSAADAH', 'level' => 'tk'],
            ['name' => 'RA AL-MA`ARIF', 'level' => 'tk'],
            ['name' => 'RA NURUR RAHMAN', 'level' => 'tk'],
            ['name' => 'RA AL-FATAA PUI', 'level' => 'tk'],
            ['name' => 'RA AL MA SUM', 'level' => 'tk'],
            ['name' => 'RA AL MUJAHIDIN', 'level' => 'tk'],
            ['name' => 'RA YASIIN', 'level' => 'tk'],
            ['name' => 'RA AL WASHLIYAH', 'level' => 'tk'],
            ['name' => 'RA NURUL IMAN', 'level' => 'tk'],
            ['name' => 'RA DARUN NAHWI', 'level' => 'tk'],
            ['name' => 'RA AL TAQWA', 'level' => 'tk'],
            ['name' => 'RA AS-SALAFIYAH', 'level' => 'tk'],
            ['name' => 'RA MA`ARIF LANGUT', 'level' => 'tk'],
            ['name' => 'RA BAITURRAHMAH', 'level' => 'tk'],
            ['name' => 'RA AL QHOZALI', 'level' => 'tk'],
            ['name' => 'RA HUBUL WATHON', 'level' => 'tk'],
            ['name' => 'RA MIFTAHUS SUBBAN', 'level' => 'tk'],
            ['name' => 'RA PUI TULUNGAGUNG', 'level' => 'tk'],
            ['name' => 'RA MASITHOH', 'level' => 'tk'],
            ['name' => 'RA AL KAROMAH', 'level' => 'tk'],
            ['name' => 'RA AL JANNAH', 'level' => 'tk'],
            ['name' => 'RA MANBAUL HUDA', 'level' => 'tk'],
            ['name' => 'RA BAITURROHIM', 'level' => 'tk'],
            ['name' => 'RA AL IKHLAS', 'level' => 'tk'],
            ['name' => 'RA AMANAH PUI', 'level' => 'tk'],
            ['name' => 'RA ATH THAHIRIYAH', 'level' => 'tk'],
            ['name' => 'RA NURUL MUTMAINAH', 'level' => 'tk'],
            ['name' => 'RA AL-MUKHLASUN', 'level' => 'tk'],
            ['name' => 'RA NURUL IMAN', 'level' => 'tk'],
            ['name' => 'RA AL TAUBAH', 'level' => 'tk'],
            ['name' => 'RA AL IKHLAS', 'level' => 'tk'],
            ['name' => 'RA AL HIKMAH', 'level' => 'tk'],
            ['name' => 'RA AL HUDA', 'level' => 'tk'],
            ['name' => 'RA ULUL ALBAB', 'level' => 'tk'],
            ['name' => 'RA AL-FURQON', 'level' => 'tk'],
            ['name' => 'RA AMALIYAH', 'level' => 'tk'],
            ['name' => 'RA NAHDLATUL ULAMA', 'level' => 'tk'],
            ['name' => 'RA MA`ARIF PRANGGONG', 'level' => 'tk'],
            ['name' => 'RA AL KHAIRIYAH', 'level' => 'tk'],
            ['name' => 'RA RAUDHATUL HUDA', 'level' => 'tk'],
            ['name' => 'RA MUSLIMAT NU AL HIDAYAH', 'level' => 'tk'],
            ['name' => 'RA AL IKHLASH', 'level' => 'tk'],
            ['name' => 'RA USWATUN HASANAH', 'level' => 'tk'],
            ['name' => 'RA DARUL FALAH', 'level' => 'tk'],
            ['name' => 'RA AZ ZAHRA', 'level' => 'tk'],
            ['name' => 'RA NURUL HUDA', 'level' => 'tk'],
            ['name' => 'RA BAITURROHIM', 'level' => 'tk'],
            ['name' => 'RA PUI WIDENG', 'level' => 'tk'],
            ['name' => 'RA ASHIBYAN', 'level' => 'tk'],
            ['name' => 'RA ASYARIFATUL NURUL ULUM', 'level' => 'tk'],
            ['name' => 'RA AL HIDAYAH', 'level' => 'tk'],
            ['name' => 'RA AL HIKMAH', 'level' => 'tk'],
            ['name' => 'RA NURUL IKHLAS', 'level' => 'tk'],
            ['name' => 'RA AT TAQWA', 'level' => 'tk'],
            ['name' => 'RA AL IKHLAS', 'level' => 'tk'],
            ['name' => 'RA MISBAHURROHMAH', 'level' => 'tk'],
            ['name' => 'RA MIFTAHUSSURUR', 'level' => 'tk'],
            ['name' => 'RA SHOLIHA', 'level' => 'tk'],
            ['name' => 'RA DADAP BARU', 'level' => 'tk'],
            ['name' => 'RA MUSLIMAT NU DARUSSALAM', 'level' => 'tk'],
            ['name' => 'RA AL ISTIQOMAH', 'level' => 'tk'],
            ['name' => 'RA AL ISHLAH', 'level' => 'tk'],
            ['name' => 'RA TARB MUTA ALLIMIN', 'level' => 'tk'],
            ['name' => 'RA AL MUSYAWIRIN', 'level' => 'tk'],
            ['name' => 'RA HIDAYATUS SIBYAN', 'level' => 'tk'],
            ['name' => 'RA MIFTAHUL ULUM', 'level' => 'tk'],
            ['name' => 'RA WALISANGA', 'level' => 'tk'],
            ['name' => 'RA AL - IKHLAS TRESNA', 'level' => 'tk'],
            ['name' => 'RA AZZAMZAMI', 'level' => 'tk'],
            ['name' => 'RA ALI RIFA`I', 'level' => 'tk'],
            ['name' => 'RA DARUSSALAM KESAN', 'level' => 'tk'],
            ['name' => 'RA EDUCATION INDONESIA', 'level' => 'tk'],
            ['name' => 'RA PELITA INSANI SUKAHAJI', 'level' => 'tk'],
            ['name' => 'RA AT TAUHID PONDOK ASEM', 'level' => 'tk'],
            ['name' => 'RA CAHAYA QOLBI ANJATAN', 'level' => 'tk'],
            ['name' => 'RA AT-TOHIRIYAH', 'level' => 'tk'],
            ['name' => 'RA ALKAUTSAR', 'level' => 'tk'],
            ['name' => 'RA NURUL JANNAH', 'level' => 'tk'],
            ['name' => 'RA NURUL HUDA', 'level' => 'tk'],
            ['name' => 'RA NURUL FITRAH', 'level' => 'tk'],
            ['name' => 'RA NAHDLOTUR RIJAL KROYA', 'level' => 'tk'],
            ['name' => 'RA MUTIARA BUNDA CIPANCUH', 'level' => 'tk'],
            ['name' => 'RA BINA INSANI KALENSARI', 'level' => 'tk'],
            ['name' => 'MIN 3 INDRAMAYU', 'level' => 'sd'],
            ['name' => 'MIN 2 INDRAMAYU', 'level' => 'sd'],
            ['name' => 'MIN 5 INDRAMAYU', 'level' => 'sd'],
            ['name' => 'MIN 4 INDRAMAYU', 'level' => 'sd'],
            ['name' => 'MIN 1 INDRAMAYU', 'level' => 'sd'],
            ['name' => 'MIS AL ISLAM', 'level' => 'sd'],
            ['name' => 'MIS BINTANG SEMBILAN', 'level' => 'sd'],
            ['name' => 'MIS PLUS LAA TAHZAN ANJATAN', 'level' => 'sd'],
            ['name' => 'MIS ASSALAM DRUNTENWETAN', 'level' => 'sd'],
            ['name' => 'MIS UNGGULAN SUMBERMULYA', 'level' => 'sd'],
            ['name' => 'MIS AL-GHOZALI JATIBARANG', 'level' => 'sd'],
            ['name' => 'MIS YAPITA', 'level' => 'sd'],
            ['name' => 'MIS NAHDLOTUR RIJAL KROYA', 'level' => 'sd'],
            ['name' => 'MIS MIFTAHUL BAROKAH', 'level' => 'sd'],
            ['name' => 'MIS SEKOLAH ALAM INDRAMAYU', 'level' => 'sd'],
            ['name' => 'MIS NU TENAJAR', 'level' => 'sd'],
            ['name' => 'MIS QUR`ANIYYAH AL-ISTIQOMAH', 'level' => 'sd'],
            ['name' => 'MIS HIDAYATUL MUBTADIIN NEW', 'level' => 'sd'],
            ['name' => 'MIS AL WARDAH', 'level' => 'sd'],
            ['name' => 'MIS NURUL IHSAN', 'level' => 'sd'],
            ['name' => 'MIS HIDAYATUS SALAFIYAH', 'level' => 'sd'],
            ['name' => 'MIS AL FUTUHIYAH', 'level' => 'sd'],
            ['name' => 'MIS ASSALAM', 'level' => 'sd'],
            ['name' => 'MIS AL-ITTIHAD DUKUHJATI', 'level' => 'sd'],
            ['name' => 'MIS PELITA INSANI SUKAHAJI', 'level' => 'sd'],
            ['name' => 'MIS BAITUL ILMI', 'level' => 'sd'],
            ['name' => 'MIS ISLAMIC CENTRE', 'level' => 'sd'],
            ['name' => 'MIS NU CANTIGI', 'level' => 'sd'],
            ['name' => 'MIS BABUR ROYYAN', 'level' => 'sd'],
            ['name' => 'MIS MIFTAHUL ULUM BOGOR', 'level' => 'sd'],
            ['name' => 'MIS PUI PATROL', 'level' => 'sd'],
            ['name' => 'MIS NURUL FATAH', 'level' => 'sd'],
            ['name' => 'MIS MIFTAHUL HUDA', 'level' => 'sd'],
            ['name' => 'MIS HUBBUL WATHON', 'level' => 'sd'],
            ['name' => 'MIS AL QOHARIYAH', 'level' => 'sd'],
            ['name' => 'MIS AT THOHIRIYAH', 'level' => 'sd'],
            ['name' => 'MIS NURUL HUDA', 'level' => 'sd'],
            ['name' => 'MIS TARBIYATUL MUTAALIMIN I', 'level' => 'sd'],
            ['name' => 'MIS TARBIYATUL MUTAALIMIN II', 'level' => 'sd'],
            ['name' => 'MIS PUI SUKAPERNA', 'level' => 'sd'],
            ['name' => 'MIS TARBIYATUL AULAD', 'level' => 'sd'],
            ['name' => 'MIS HIDAYATUL MUBTADIIN', 'level' => 'sd'],
            ['name' => 'MIS MA`ARIF PRANGGONG', 'level' => 'sd'],
            ['name' => 'MIS NU CIDEMPET', 'level' => 'sd'],
            ['name' => 'MIS RAUDHATUL HUDA', 'level' => 'sd'],
            ['name' => 'MIS NURUL ULUM', 'level' => 'sd'],
            ['name' => 'MIS NURUL HUDA', 'level' => 'sd'],
            ['name' => 'MIS MIFTAHUL ULUM V', 'level' => 'sd'],
            ['name' => 'MIS AL BASYARIYAH', 'level' => 'sd'],
            ['name' => 'MIS MA HAD AL-ZAYTUN', 'level' => 'sd'],
            ['name' => 'MIS AL ISHLAH', 'level' => 'sd'],
            ['name' => 'MIS AL FATAH', 'level' => 'sd'],
            ['name' => 'MIS DARUSSALAM', 'level' => 'sd'],
            ['name' => 'MIS AL IKHLASH', 'level' => 'sd'],
            ['name' => 'MIS USWATUN HASANAH', 'level' => 'sd'],
            ['name' => 'MIS TWT LUNGMALANG', 'level' => 'sd'],
            ['name' => 'MIS AL HIKMAMUSSALAFIYAH', 'level' => 'sd'],
            ['name' => 'MIS MUHAMMADIYAH SUKAURIP', 'level' => 'sd'],
            ['name' => 'MIS MUHAMMADIYAH TEGALURUNG', 'level' => 'sd'],
            ['name' => 'MIS ISLAMIYAH TEGALURUNG', 'level' => 'sd'],
            ['name' => 'MIS TWT KARANGANYAR', 'level' => 'sd'],
            ['name' => 'MIS TWT KARANG JAYA', 'level' => 'sd'],
            ['name' => 'MIS TWT BODAS', 'level' => 'sd'],
            ['name' => 'MIS KULIYATUS SIBYAN', 'level' => 'sd'],
            ['name' => 'MIS ISLAMIYAH DUKUHJATI', 'level' => 'sd'],
            ['name' => 'MIS HIDAYATUS SHIBYAN', 'level' => 'sd'],
            ['name' => 'MIS PUI TULUNGAGUNG', 'level' => 'sd'],
            ['name' => 'MIS PUI TENAJAR LOR 2', 'level' => 'sd'],
            ['name' => 'MIS PUI TENAJAR LOR 1', 'level' => 'sd'],
            ['name' => 'MIS NURUL HUDA SUKAWERA', 'level' => 'sd'],
            ['name' => 'MIS HIDAYATUL MUBTADIIN', 'level' => 'sd'],
            ['name' => 'MIS ASY-SYAFIIYYAH', 'level' => 'sd'],
            ['name' => 'MIS AL-FALAH', 'level' => 'sd'],
            ['name' => 'MIS TARBIYATUL ISLAMIYAH', 'level' => 'sd'],
            ['name' => 'MIS MIFTAHUL HUDA SOGA', 'level' => 'sd'],
            ['name' => 'MIS MAMBAUL ULUM', 'level' => 'sd'],
            ['name' => 'MIS GUPPI TENAJAR KIDUL', 'level' => 'sd'],
            ['name' => 'MIS AL-ISLAMIYAH', 'level' => 'sd'],
            ['name' => 'MIS AL-BAROKAH', 'level' => 'sd'],
            ['name' => 'MIS AL WATHONIYAH', 'level' => 'sd'],
            ['name' => 'MIS ISLAMIYAH', 'level' => 'sd'],
            ['name' => 'MIS FATHUL ULUM', 'level' => 'sd'],
            ['name' => 'MIS PUI UJUNGARIS', 'level' => 'sd'],
            ['name' => 'MIS TARBIYAH ISLAMIYAH BANGODUA', 'level' => 'sd'],
            ['name' => 'MIS BITSATUL ISLAMIYAH', 'level' => 'sd'],
            ['name' => 'MIS HIDAYATUL MUTTAQIEN', 'level' => 'sd'],
            ['name' => 'MIS ASSALAMIYAH', 'level' => 'sd'],
            ['name' => 'MIS PUI MEKARJATI', 'level' => 'sd'],
            ['name' => 'MIS DARURROHMAN', 'level' => 'sd'],
            ['name' => 'MIS AL MUSYAHADAH', 'level' => 'sd'],
            ['name' => 'MIS AL IRSYAD AL ISLAMIYAH', 'level' => 'sd'],
            ['name' => 'MIS PUI HAURKOLOT', 'level' => 'sd'],
            ['name' => 'MIS NURUL HIKMAH', 'level' => 'sd'],
            ['name' => 'MIS MUHAMMADIYAH', 'level' => 'sd'],
            ['name' => 'MIS GUPPI CININI', 'level' => 'sd'],
            ['name' => 'MIS GUPPI DARUSSALAM', 'level' => 'sd'],
            ['name' => 'MIS DARUL FALAH', 'level' => 'sd'],
            ['name' => 'MIS AL WASHLIYAH', 'level' => 'sd'],
            ['name' => 'MIS TWT BEDENG SATU', 'level' => 'sd'],
            ['name' => 'MIS PUI ANJATAN BARU', 'level' => 'sd'],
            ['name' => 'MIS INFARUL GHOY', 'level' => 'sd'],
            ['name' => 'MIS HIDAYATUL MUBTADIIN', 'level' => 'sd'],
            ['name' => 'MIS NU KARANGANYAR', 'level' => 'sd'],
            ['name' => 'MIS MA`ARIF KARANGANYAR', 'level' => 'sd'],
            ['name' => 'MIS PUI KEMPED', 'level' => 'sd'],
            ['name' => 'MIS AL IKHLAS ERETAN', 'level' => 'sd'],
            ['name' => 'MIS RAUDHLATUL MUTAALIMIN', 'level' => 'sd'],
            ['name' => 'MIS GUPPI TELUKAGUNG', 'level' => 'sd'],
            ['name' => 'MIS GUPPI LOSARANG', 'level' => 'sd'],
            ['name' => 'MIS DARUL HIKMAH', 'level' => 'sd'],
            ['name' => 'MIS PUI DERMAYU', 'level' => 'sd'],
            ['name' => 'MIS MATHLA UL ANWAR', 'level' => 'sd'],
            ['name' => 'MIS DARUN NAHWI', 'level' => 'sd'],
            ['name' => 'MIS ASSALAFIYAH', 'level' => 'sd'],
            ['name' => 'MIS PUI FATAHILLAH', 'level' => 'sd'],
            ['name' => 'MIS PUI PAMAYAHAN', 'level' => 'sd'],
            ['name' => 'MIS GUPPI AR-RAHMAN DUKUH', 'level' => 'sd'],
            ['name' => 'MIS YAPIDA', 'level' => 'sd'],
            ['name' => 'MIS NURUZHZHOLAM', 'level' => 'sd'],
            ['name' => 'MIS MA`ARIF LEGOK', 'level' => 'sd'],
            ['name' => 'MIS MA`ARIF LANGUT', 'level' => 'sd'],
            ['name' => 'MIS PUI JATISAWIT LOR', 'level' => 'sd'],
            ['name' => 'MIS NURUSSAADAH', 'level' => 'sd'],
            ['name' => 'MIS MUHAMMADIYAH', 'level' => 'sd'],
            ['name' => 'MIS MIFTAHUL HUDA', 'level' => 'sd'],
            ['name' => 'MIS MA`ARIF SEGERAN KIDUL', 'level' => 'sd'],
            ['name' => 'MIS PUI SEGERAN KIDUL', 'level' => 'sd'],
            ['name' => 'MIS PUI JUNTIKEBON', 'level' => 'sd'],
            ['name' => 'MIS ISLAMIYAH PULAK', 'level' => 'sd'],
            ['name' => 'MIS ISLAMIYAH JUNTIKEBON', 'level' => 'sd'],
            ['name' => 'MIS ISLAMIYAH DADAP', 'level' => 'sd'],
            ['name' => 'MIS AL MUJAHIDIN', 'level' => 'sd'],
            ['name' => 'MIS DARUL ULUM', 'level' => 'sd'],
            ['name' => 'MIS AL-QURANIYAH', 'level' => 'sd'],
            ['name' => 'MIS RAUDLATUS SHIBYAN', 'level' => 'sd'],
            ['name' => 'MIS MIFTAHUL HUDA', 'level' => 'sd'],
            ['name' => 'MIS RAUDLATUT THULLAB', 'level' => 'sd'],
            ['name' => 'MIS MIFTAHUL ULUM II', 'level' => 'sd'],
            ['name' => 'MIS HIDAYATUS SHIBYAN', 'level' => 'sd'],
            ['name' => 'MIS HIDAYATUL MUBTADIIN', 'level' => 'sd'],
            ['name' => 'MIS PUI WIDENG', 'level' => 'sd'],
            ['name' => 'MIS GUPPI NYONGAT', 'level' => 'sd'],
            ['name' => 'MIS GUPPI BRUNGUT', 'level' => 'sd'],
            ['name' => 'MIS ASSYIFA WAL AIN', 'level' => 'sd'],
            ['name' => 'MIS PUI GRABYAGAN', 'level' => 'sd'],
            ['name' => 'MIS MIFTAHUL HUDA', 'level' => 'sd'],
            ['name' => 'MIS HIDAYATUL MUBTADI IN 1 CIBEBER', 'level' => 'sd'],
            ['name' => 'MIS HIDAYATUL MUBTADI IN 2 CIBEBER', 'level' => 'sd'],
            ['name' => 'MI HUSNUL KHOTIMAH', 'level' => 'sd'],
            ['name' => 'MI AL JABBAR', 'level' => 'sd'],
            ['name' => 'MI TERPADU AL-AWSATH', 'level' => 'sd'],
            ['name' => 'MI UNGGULAN MUHAMMADIYAH INDRAMAYU', 'level' => 'sd'],
            ['name' => 'MI TAMBA ATI', 'level' => 'sd'],
            ['name' => 'MI ALMUTA`ALIMIN SUKAGUMIWANG', 'level' => 'sd'],
            ['name' => 'MI NUUR AL HABSY SIDADADI', 'level' => 'sd'],
            ['name' => 'MI AL - ABROOR', 'level' => 'sd'],
            ['name' => 'MI NURUL JANNAH', 'level' => 'sd'],
            ['name' => 'MI NURUL YAQIN', 'level' => 'sd'],
            ['name' => 'MTSS AL MUSYAHADAH HAURGEULIS', 'level' => 'smp'],
            ['name' => 'MTSS AL-IRSYAD AL-ISLAMIYYAH', 'level' => 'smp'],
            ['name' => 'MTSS AN-NUR', 'level' => 'smp'],
            ['name' => 'MTSS NURUL HIKMAH HAURGEULIS', 'level' => 'smp'],
            ['name' => 'MTSS GUPPI GABUSWETAN', 'level' => 'smp'],
            ['name' => 'MTSS NU TEGAL PELEM', 'level' => 'smp'],
            ['name' => 'MTSS BITSATUL ISLAM', 'level' => 'smp'],
            ['name' => 'MTSS FATHUL ULUM', 'level' => 'smp'],
            ['name' => 'MTSS MAMBAUL ULUM', 'level' => 'smp'],
            ['name' => 'MTSS MA`ARIF SUKASLAMET', 'level' => 'smp'],
            ['name' => 'MTSS AL ISHLAH SUMURADEM', 'level' => 'smp'],
            ['name' => 'MTSS AL WASHLIYAH SUKRA', 'level' => 'smp'],
            ['name' => 'MTSS MA`ARIF NURUL ULUM SUKRA', 'level' => 'smp'],
            ['name' => 'MTSS AL HIKMAH CIDEMPET', 'level' => 'smp'],
            ['name' => 'MTSS NU CANTIGI', 'level' => 'smp'],
            ['name' => 'MTSS GUPPI MANGGUNGAN', 'level' => 'smp'],
            ['name' => 'MTSS MA`ARIF KENDAYAKAN', 'level' => 'smp'],
            ['name' => 'MTSS NU RAJASINGA', 'level' => 'smp'],
            ['name' => 'MTSS AL BASYARIYAH KEDOKAN BUNDER', 'level' => 'smp'],
            ['name' => 'MTSS MIFTAHUL HUDA', 'level' => 'smp'],
            ['name' => 'MTSS DARUL HIKMAH PANGKALAN', 'level' => 'smp'],
            ['name' => 'MTSS AL MUCHLASUN WIRAKANAN', 'level' => 'smp'],
            ['name' => 'MTSS HASANUDIN ERETAN', 'level' => 'smp'],
            ['name' => 'MTSS MA`ARIF KANDANGHAUR', 'level' => 'smp'],
            ['name' => 'MTSS AL-HIJRAH BONGAS', 'level' => 'smp'],
            ['name' => 'MTSS DARUL FALAH', 'level' => 'smp'],
            ['name' => 'MTSS AL AMIN ANJATAN', 'level' => 'smp'],
            ['name' => 'MTSS AL JAMIYATUL WASHLIYAH ANJATAN', 'level' => 'smp'],
            ['name' => 'MTSS MA`ARIF MIFTAHUL HUDA', 'level' => 'smp'],
            ['name' => 'MTSS DARUL IKHLASH SUKAURIP', 'level' => 'smp'],
            ['name' => 'MTSS HIDAYATUL MA`ARIF TEMIYANG', 'level' => 'smp'],
            ['name' => 'MTSS YAPIDA SLIYEG', 'level' => 'smp'],
            ['name' => 'MTSS AL GHOZALI', 'level' => 'smp'],
            ['name' => 'MTSS DARUSSALAM SUKALILA', 'level' => 'smp'],
            ['name' => 'MTSS AL MA`ARIF LEGOK', 'level' => 'smp'],
            ['name' => 'MTSS AL MUMINIEN', 'level' => 'smp'],
            ['name' => 'MTSS MA`ARIF LANGUT', 'level' => 'smp'],
            ['name' => 'MTSS ULFA PRANGGONG', 'level' => 'smp'],
            ['name' => 'MTSS DARUN NAHWI', 'level' => 'smp'],
            ['name' => 'MTSS YAPIIM DUKUH', 'level' => 'smp'],
            ['name' => 'MTSS AL WASHLIYAH SINDANG', 'level' => 'smp'],
            ['name' => 'MTSS PUI TENAJAR', 'level' => 'smp'],
            ['name' => 'MTSS YAPIN KERTASEMAYA', 'level' => 'smp'],
            ['name' => 'MTSS RABITHTATUL ULUM', 'level' => 'smp'],
            ['name' => 'MTSS AL-MA`ARIF KARANG AMPEL', 'level' => 'smp'],
            ['name' => 'MTSS AL MUJAHIDIN', 'level' => 'smp'],
            ['name' => 'MTSS GUPPI JUNTINYUAT', 'level' => 'smp'],
            ['name' => 'MTSS MANBAUL BAHRI', 'level' => 'smp'],
            ['name' => 'MTSS PUI SEGERAN KIDUL', 'level' => 'smp'],
            ['name' => 'MTSS AS SAKIENAH BOARDING SCHOOL', 'level' => 'smp'],
            ['name' => 'MTSS DARUL MA`ARIF SLIYEG', 'level' => 'smp'],
            ['name' => 'MTSS HIDAYATUSSHIBYAN', 'level' => 'smp'],
            ['name' => 'MTSS NU YASMIN', 'level' => 'smp'],
            ['name' => 'MTSS DARUS SALAM LOMBANG', 'level' => 'smp'],
            ['name' => 'MTSS BANI YASIN', 'level' => 'smp'],
            ['name' => 'MTSS AL-MAGHFUROH CIPAAT', 'level' => 'smp'],
            ['name' => 'MTSS SEKOLAH ALAM INDRAMAYU', 'level' => 'smp'],
            ['name' => 'MTSS PLUS BINA PRESTASI ISLAMI', 'level' => 'smp'],
            ['name' => 'MTSS KARANGMANGGU', 'level' => 'smp'],
            ['name' => 'MTSS NUSANTARA', 'level' => 'smp'],
            ['name' => 'MTSS KHAIRU UMMAH', 'level' => 'smp'],
            ['name' => 'MTSS KH AHMAD RIFA`I', 'level' => 'smp'],
            ['name' => 'MTSS NU PATROL', 'level' => 'smp'],
            ['name' => 'MTSS MA`ARIF AL FATAH', 'level' => 'smp'],
            ['name' => 'MTSS NURUL ISLAM ARJASARI', 'level' => 'smp'],
            ['name' => 'MTSS AS SYIFA WAL AIN BONDAN', 'level' => 'smp'],
            ['name' => 'MTSS CADANGPINGGAN', 'level' => 'smp'],
            ['name' => 'MTSS YA ABIDI', 'level' => 'smp'],
            ['name' => 'MTSS MA HAD AL-ZAYTUN', 'level' => 'smp'],
            ['name' => 'MTSS NURUL HIKMAH GANTAR', 'level' => 'smp'],
            ['name' => 'MTSS AL HIDAYAH PATROL BARU', 'level' => 'smp'],
            ['name' => 'MTSS MA`ARIF BUGEL AN-NUR', 'level' => 'smp'],
            ['name' => 'MTSS NU MAMBAUL HIKAM', 'level' => 'smp'],
            ['name' => 'MTSS PERCONTOHAN INSAN CENDEKIA', 'level' => 'smp'],
            ['name' => 'MTSS AL GHIFARI', 'level' => 'smp'],
            ['name' => 'MTSS AL IKHLAS', 'level' => 'smp'],
            ['name' => 'MTSN 13 INDRAMAYU', 'level' => 'smp'],
            ['name' => 'MTSN 11 INDRAMAYU', 'level' => 'smp'],
            ['name' => 'MTSN 5 INDRAMAYU', 'level' => 'smp'],
            ['name' => 'MTSN 4 INDRAMAYU', 'level' => 'smp'],
            ['name' => 'MTSN 10 INDRAMAYU', 'level' => 'smp'],
            ['name' => 'MTSN 2 INDRAMAYU', 'level' => 'smp'],
            ['name' => 'MTSN 6 INDRAMAYU', 'level' => 'smp'],
            ['name' => 'MTSN 8 INDRAMAYU', 'level' => 'smp'],
            ['name' => 'MTSN 9 INDRAMAYU', 'level' => 'smp'],
            ['name' => 'MTSN 7 INDRAMAYU', 'level' => 'smp'],
            ['name' => 'MTSN 12 INDRAMAYU', 'level' => 'smp'],
            ['name' => 'MTSN 3 INDRAMAYU', 'level' => 'smp'],
            ['name' => 'MTSN 1 INDRAMAYU', 'level' => 'smp'],
            ['name' => 'MTs NASYRUL ULUM', 'level' => 'smp'],
            ['name' => 'MTs NU HAURGEULIS', 'level' => 'smp'],
            ['name' => 'MTs AL IHSAN', 'level' => 'smp'],
            ['name' => 'MA INSAN MADANI', 'level' => 'sma'],
            ['name' => 'MAN 1 INDRAMAYU', 'level' => 'sma'],
            ['name' => 'MAN 2 INDRAMAYU', 'level' => 'sma'],
            ['name' => 'MAN 3 INDRAMAYU', 'level' => 'sma'],
            ['name' => 'MAS AL AMIN', 'level' => 'sma'],
            ['name' => 'MAS AL IRSYAD AL ISLAMIYYAH', 'level' => 'sma'],
            ['name' => 'MAS AL LATIEFIYAH', 'level' => 'sma'],
            ['name' => 'MAS AL WATHONIYAH CIKEDUNG', 'level' => 'sma'],
            ['name' => 'MAS AL-SYARIFIYAH BONDAN', 'level' => 'sma'],
            ['name' => 'MAS ARIF PRANGGONG', 'level' => 'sma'],
            ['name' => 'MAS AS-SAKIENAH BOARDING SCHOOL', 'level' => 'sma'],
            ['name' => 'MAS ASY-SYAFI IYAH TERPADU', 'level' => 'sma'],
            ['name' => 'MAS CADANGPINGGAN', 'level' => 'sma'],
            ['name' => 'MAS DARUL FALAH', 'level' => 'sma'],
            ['name' => 'MAS DARUN NAHWI', 'level' => 'sma'],
            ['name' => 'MAS DARUSSALAM SUKALILA', 'level' => 'sma'],
            ['name' => 'MAS FATAHILLAH', 'level' => 'sma'],
            ['name' => 'MAS GUPPI BANGODUA', 'level' => 'sma'],
            ['name' => 'MAS GUPPI CIKEDUNG', 'level' => 'sma'],
            ['name' => 'MAS HIDAYATUL MUBTADIEN', 'level' => 'sma'],
            ['name' => 'MAS HIDAYATUN NASYI IEN', 'level' => 'sma'],
            ['name' => 'MAS MA`HAD AL ZAYTUN', 'level' => 'sma'],
            ['name' => 'MAS MISAYA MINA KANDANGHAUR', 'level' => 'sma'],
            ['name' => 'MAS NU PATROL', 'level' => 'sma'],
            ['name' => 'MAS NURUL HIKMAH HAURGEULIS', 'level' => 'sma'],
            ['name' => 'MAS PESANTREN AL MU MINIEN', 'level' => 'sma'],
            ['name' => 'MAS PESANTREN AL-URWATUL WUTSQO', 'level' => 'sma'],
            ['name' => 'MAS PRINGGABAYA', 'level' => 'sma'],
            ['name' => 'MAS PUI TENAJAR LOR', 'level' => 'sma'],
            ['name' => 'MAS RABITHATUL ULUM', 'level' => 'sma'],
            ['name' => 'MAS YA ABIDI TUKDANA', 'level' => 'sma'],
            ['name' => 'MAS YAPIN KERTASEMAYA', 'level' => 'sma'],
        ];

        $this->table('institutions')->insert($data)->saveData();
    }
}
